# Generated by Django 4.1 on 2023-02-24 08:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.models.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('awaiting', 'Awaiting'), ('completed', 'Completed'), ('outdated', 'Outdated'), ('rejected', 'Rejected')], default='waiting', max_length=255, verbose_name='Status')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Created At')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Payment Date')),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[utils.models.validators.positive_validator], verbose_name='Expected Amount ($)')),
                ('current_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[utils.models.validators.positive_validator], verbose_name='Current Amount ($)')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[utils.models.validators.positive_validator], verbose_name='Amount ($)')),
                ('status', models.CharField(choices=[('awaiting', 'Awaiting'), ('completed', 'Completed'), ('outdated', 'Outdated'), ('rejected', 'Rejected')], default='waiting', max_length=255, verbose_name='Status')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Created At')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Payment Date')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finance.invoice', verbose_name='Invoice')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
