# Generated by Django 4.1 on 2023-02-28 09:22

from django.db import migrations, models
import utils.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='completion',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[utils.models.validators.positive_validator], verbose_name='Completion (%)'),
        ),
    ]
