# Generated by Django 4.1 on 2023-03-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_invoice_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='actual_date',
            field=models.DateField(blank=True, null=True, verbose_name='Actual Date'),
        ),
        migrations.AddField(
            model_name='payment',
            name='actual_date',
            field=models.DateField(blank=True, null=True, verbose_name='Actual Date'),
        ),
    ]
