# Generated by Django 4.1 on 2023-02-24 17:56

from django.db import migrations, models
import django_lifecycle.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreprocessingHandlers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='stage',
            name='max_delivery_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Maximum Delivery End Date'),
        ),
        migrations.AddField(
            model_name='stage',
            name='median_delivery_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Median Delivery End Date'),
        ),
        migrations.AddField(
            model_name='stage',
            name='min_delivery_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Minimum Delivery End Date'),
        ),
    ]
