# Generated by Django 4.1 on 2023-02-25 14:01

from django.db import migrations, models
import utils.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0003_stage_start_date_alter_feature_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='completion',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[utils.models.validators.positive_validator], verbose_name='Completion (%)'),
        ),
        migrations.AddField(
            model_name='project',
            name='completion',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[utils.models.validators.positive_validator], verbose_name='Completion (%)'),
        ),
        migrations.AddField(
            model_name='stage',
            name='completion',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[utils.models.validators.positive_validator], verbose_name='Completion (%)'),
        ),
    ]
