# Generated by Django 4.1 on 2023-02-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0004_feature_completion_project_completion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='qa_status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('ready_to_test', 'Ready To Test'), ('passed', 'Passed'), ('reverted', 'Reverted')], default='waiting', max_length=255, verbose_name='QA Status'),
        ),
    ]
