# Generated by Django 4.1 on 2023-02-25 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0005_task_qa_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='qa_status',
        ),
    ]
