# Generated by Django 4.1 on 2023-03-01 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0010_remove_feature_completion_remove_project_completion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='development.stage', verbose_name='Stage'),
        ),
        migrations.AlterField(
            model_name='project',
            name='current_status',
            field=models.CharField(choices=[('active_development', 'Active Development'), ('supporting', 'Supporting'), ('closed_for_good', 'Closed For Good')], max_length=255, null=True, verbose_name='Current Status'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='development.project', verbose_name='Project'),
        ),
    ]
