# Generated by Django 4.1 on 2023-03-02 08:39

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0011_alter_feature_stage_alter_project_current_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(default='\n<p style="margin-left:0px;">\n    <strong>Описание:</strong>\n</p>\n<p style="margin-left:0px;">\n    <strong>Ссылка:</strong>\n</p>\n<p style="margin-left:0px;">\n    <strong>Логин:</strong>\n</p>\n<p style="margin-left:0px;">\n    <strong>Пароль:</strong>\n</p>\n<p style="margin-left:0px;">\n    <strong>Действия:</strong>\n</p>\n', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(default='\n<p style="margin-left:0px;">\n    <strong>Постановка задачи:</strong>\n</p>\n<p style="margin-left:0px;">\n    <strong>Предложения по реализации:</strong>\n</p>\n<p style="margin-left:0px;">\n    <strong>Результат:</strong>\n</p>\n', verbose_name='Description'),
        ),
    ]
