# Generated by Django 4.1 on 2023-03-03 08:47

from django.db import migrations, models
import utils.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0013_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='max_hours_for_qa',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[utils.models.validators.positive_validator], verbose_name='Maximum Hours For QA'),
        ),
        migrations.AddField(
            model_name='task',
            name='median_hours_for_qa',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[utils.models.validators.positive_validator], verbose_name='Median Hours For QA'),
        ),
        migrations.AddField(
            model_name='task',
            name='min_hours_for_qa',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[utils.models.validators.positive_validator], verbose_name='Minimum Hours For QA'),
        ),
    ]
