# Generated by Django 4.1 on 2023-03-03 09:40

from decimal import Decimal
from django.db import migrations, models
import utils.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0014_task_max_hours_for_qa_task_median_hours_for_qa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='max_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[utils.models.validators.positive_validator], verbose_name='Maximum Cost ($)'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='median_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[utils.models.validators.positive_validator], verbose_name='Median Cost ($)'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='min_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[utils.models.validators.positive_validator], verbose_name='Minimum Cost ($)'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='max_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[utils.models.validators.positive_validator], verbose_name='Maximum Cost ($)'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='median_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[utils.models.validators.positive_validator], verbose_name='Median Cost ($)'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='min_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[utils.models.validators.positive_validator], verbose_name='Minimum Cost ($)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='max_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[utils.models.validators.positive_validator], verbose_name='Maximum Cost ($)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='median_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[utils.models.validators.positive_validator], verbose_name='Median Cost ($)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='min_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[utils.models.validators.positive_validator], verbose_name='Minimum Cost ($)'),
        ),
    ]
