# Generated by Django 4.1 on 2023-03-03 09:42

from decimal import Decimal
from django.db import migrations, models
import utils.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0015_alter_feature_max_cost_alter_feature_median_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='max_hours_for_delivery',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[utils.models.validators.positive_validator], verbose_name='Maximum Hours For Delivery'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='median_hours_for_delivery',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[utils.models.validators.positive_validator], verbose_name='Median Hours For Delivery'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='min_hours_for_delivery',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[utils.models.validators.positive_validator], verbose_name='Minimum Hours For Delivery'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='max_hours_for_delivery',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[utils.models.validators.positive_validator], verbose_name='Maximum Hours For Delivery'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='median_hours_for_delivery',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[utils.models.validators.positive_validator], verbose_name='Median Hours For Delivery'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='min_hours_for_delivery',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[utils.models.validators.positive_validator], verbose_name='Minimum Hours For Delivery'),
        ),
        migrations.AlterField(
            model_name='task',
            name='max_hours_for_delivery',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[utils.models.validators.positive_validator], verbose_name='Maximum Hours For Delivery'),
        ),
        migrations.AlterField(
            model_name='task',
            name='median_hours_for_delivery',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[utils.models.validators.positive_validator], verbose_name='Median Hours For Delivery'),
        ),
        migrations.AlterField(
            model_name='task',
            name='min_hours_for_delivery',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[utils.models.validators.positive_validator], verbose_name='Minimum Hours For Delivery'),
        ),
    ]
