# Generated by Django 4.1 on 2023-03-08 07:40

from decimal import Decimal
from django.db import migrations, models
import utils.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0016_alter_feature_max_hours_for_delivery_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='median_hours_for_qa',
            new_name='qa_hours',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='completion_delivery',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='completion_development',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='max_cost',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='max_delivery_end_date',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='max_hours_for_delivery',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='median_cost',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='median_delivery_end_date',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='median_hours_for_delivery',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='min_cost',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='min_delivery_end_date',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='min_hours_for_delivery',
        ),
        migrations.RemoveField(
            model_name='project',
            name='completion_delivery',
        ),
        migrations.RemoveField(
            model_name='project',
            name='completion_development',
        ),
        migrations.RemoveField(
            model_name='project',
            name='estimated_cost',
        ),
        migrations.RemoveField(
            model_name='project',
            name='excpected_end',
        ),
        migrations.RemoveField(
            model_name='project',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='completion_delivery',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='completion_development',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='max_cost',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='max_delivery_end_date',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='max_hours_for_delivery',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='median_cost',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='median_delivery_end_date',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='median_hours_for_delivery',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='min_cost',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='min_delivery_end_date',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='min_hours_for_delivery',
        ),
        migrations.RemoveField(
            model_name='task',
            name='complexity',
        ),
        migrations.RemoveField(
            model_name='task',
            name='max_cost',
        ),
        migrations.RemoveField(
            model_name='task',
            name='max_delivery_end_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='max_development_end_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='max_hours_for_delivery',
        ),
        migrations.RemoveField(
            model_name='task',
            name='max_hours_for_development',
        ),
        migrations.RemoveField(
            model_name='task',
            name='max_hours_for_qa',
        ),
        migrations.RemoveField(
            model_name='task',
            name='median_cost',
        ),
        migrations.RemoveField(
            model_name='task',
            name='median_delivery_end_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='median_development_end_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='median_hours_for_delivery',
        ),
        migrations.RemoveField(
            model_name='task',
            name='median_hours_for_development',
        ),
        migrations.RemoveField(
            model_name='task',
            name='min_cost',
        ),
        migrations.RemoveField(
            model_name='task',
            name='min_delivery_end_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='min_development_end_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='min_hours_for_delivery',
        ),
        migrations.RemoveField(
            model_name='task',
            name='min_hours_for_development',
        ),
        migrations.RemoveField(
            model_name='task',
            name='min_hours_for_qa',
        ),
        migrations.RemoveField(
            model_name='task',
            name='risk',
        ),
        migrations.AddField(
            model_name='feature',
            name='actual_delivery_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Actual Delivery End Date'),
        ),
        migrations.AddField(
            model_name='feature',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[utils.models.validators.positive_validator], verbose_name='Cost ($)'),
        ),
        migrations.AddField(
            model_name='feature',
            name='delivery_completion',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[utils.models.validators.positive_validator], verbose_name='Delivery Completion (%)'),
        ),
        migrations.AddField(
            model_name='feature',
            name='delivery_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Delivery End Date'),
        ),
        migrations.AddField(
            model_name='feature',
            name='delivery_hour',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[utils.models.validators.positive_validator], verbose_name='Delivery Hours'),
        ),
        migrations.AddField(
            model_name='feature',
            name='development_completion',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[utils.models.validators.positive_validator], verbose_name='Development Completion (%)'),
        ),
        migrations.AddField(
            model_name='project',
            name='delivery_completion',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[utils.models.validators.positive_validator], verbose_name='Delivery Completion (%)'),
        ),
        migrations.AddField(
            model_name='project',
            name='development_completion',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[utils.models.validators.positive_validator], verbose_name='Development Completion (%)'),
        ),
        migrations.AddField(
            model_name='stage',
            name='actual_delivery_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Actual Delivery End Date'),
        ),
        migrations.AddField(
            model_name='stage',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[utils.models.validators.positive_validator], verbose_name='Cost ($)'),
        ),
        migrations.AddField(
            model_name='stage',
            name='delivery_completion',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[utils.models.validators.positive_validator], verbose_name='Delivery Completion (%)'),
        ),
        migrations.AddField(
            model_name='stage',
            name='delivery_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Delivery End Date'),
        ),
        migrations.AddField(
            model_name='stage',
            name='delivery_hour',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[utils.models.validators.positive_validator], verbose_name='Delivery Hours'),
        ),
        migrations.AddField(
            model_name='stage',
            name='development_completion',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[utils.models.validators.positive_validator], verbose_name='Development Completion (%)'),
        ),
        migrations.AddField(
            model_name='task',
            name='actual_delivery_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Actual Delivery End Date'),
        ),
        migrations.AddField(
            model_name='task',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[utils.models.validators.positive_validator], verbose_name='Cost ($)'),
        ),
        migrations.AddField(
            model_name='task',
            name='delivery_completion',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[utils.models.validators.positive_validator], verbose_name='Delivery Completion (%)'),
        ),
        migrations.AddField(
            model_name='task',
            name='delivery_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Delivery End Date'),
        ),
        migrations.AddField(
            model_name='task',
            name='delivery_hour',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[utils.models.validators.positive_validator], verbose_name='Delivery Hours'),
        ),
        migrations.AddField(
            model_name='task',
            name='development_completion',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[utils.models.validators.positive_validator], verbose_name='Development Completion (%)'),
        ),
        migrations.AddField(
            model_name='task',
            name='development_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Development End Date'),
        ),
        migrations.AddField(
            model_name='task',
            name='development_hour',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[utils.models.validators.positive_validator], verbose_name='Development Hours'),
        ),
    ]
