# Generated by Django 4.1 on 2023-03-08 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0018_alter_feature_start_date_alter_stage_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='delivery_completion',
        ),
        migrations.RemoveField(
            model_name='task',
            name='development_completion',
        ),
    ]
