# Generated by Django 4.1 on 2023-03-08 09:18

from django.db import migrations, models
import utils.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0019_remove_task_delivery_completion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='qa_hours',
        ),
        migrations.AddField(
            model_name='task',
            name='qa_hour',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[utils.models.validators.positive_validator], verbose_name='QA Hours'),
        ),
    ]
