# Generated by Django 4.1 on 2023-03-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0020_remove_task_qa_hours_task_qa_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Start Date'),
        ),
    ]
