# Generated by Django 4.1 on 2023-03-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0024_alter_task_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(null=True, verbose_name='Start Date'),
        ),
    ]
