# Generated by Django 4.1 on 2023-03-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0025_alter_task_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='jira_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Jira Code'),
        ),
        migrations.AddField(
            model_name='feature',
            name='jira_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Jira ID'),
        ),
        migrations.AddField(
            model_name='project',
            name='jira_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Jira Code'),
        ),
        migrations.AddField(
            model_name='project',
            name='jira_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Jira ID'),
        ),
        migrations.AddField(
            model_name='stage',
            name='jira_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Jira Code'),
        ),
        migrations.AddField(
            model_name='stage',
            name='jira_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Jira ID'),
        ),
        migrations.AddField(
            model_name='task',
            name='jira_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Jira Code'),
        ),
        migrations.AddField(
            model_name='task',
            name='jira_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Jira ID'),
        ),
    ]
