# Generated by Django 4.1 on 2023-03-30 12:09

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0026_feature_jira_code_feature_jira_id_project_jira_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=mdeditor.fields.MDTextField(default='\n<p style="margin-left:0px;">\n    <strong>Постановка задачи:</strong>\n</p>\n<p style="margin-left:0px;">\n    <strong>Предложения по реализации:</strong>\n</p>\n<p style="margin-left:0px;">\n    <strong>Результат:</strong>\n</p>\n', verbose_name='Description'),
        ),
    ]
