# Generated by Django 4.1 on 2023-03-30 12:14

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0027_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=mdeditor.fields.MDTextField(default='\n# **Постановка задачи:**\n# **Предложение по реализации**:\n# **Результат**:\n', verbose_name='Description'),
        ),
    ]
