# Generated by Django 4.1 on 2023-03-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0028_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='jira_code',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Jira Code'),
        ),
    ]
