# Generated by Django 4.1 on 2023-03-09 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0021_alter_feature_start_date_alter_stage_start_date_and_more'),
        ('sales', '0003_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='sales.source', verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='development.project', verbose_name='Project'),
        ),
    ]
