# Generated by Django 4.1 on 2023-03-10 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0004_contact_source_alter_deal_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to=settings.AUTH_USER_MODEL, verbose_name='Sales Manager'),
        ),
    ]
