# Generated by Django 4.1 on 2023-03-15 07:31

from django.db import migrations, models
import utils.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_contact_position_alter_deal_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[utils.models.validators.positive_validator], verbose_name='Amount ($)'),
        ),
    ]
