# Generated by Django 4.1 on 2023-03-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_alter_deal_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='position',
            field=models.CharField(max_length=255, null=True, verbose_name='Position'),
        ),
    ]
