# Generated by Django 4.1 on 2023-04-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_alter_deal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='actual_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Actual End Date'),
        ),
        migrations.AddField(
            model_name='deal',
            name='development_status',
            field=models.CharField(choices=[('rated', 'Rated'), ('started', 'Started'), ('completed', 'Completed')], default='rated', max_length=255, verbose_name='Development Status'),
        ),
        migrations.AddField(
            model_name='deal',
            name='end_date',
            field=models.DateField(null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='deal',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Start Date'),
        ),
    ]
