# Generated by Django 4.1 on 2023-04-19 18:56

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_meetingnotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingnotes',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
    ]
