# Generated by Django 4.1 on 2023-05-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_alter_meetingnotes_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingnotes',
            name='prompt',
            field=models.TextField(null=True, verbose_name='Prompts'),
        ),
        migrations.AddField(
            model_name='meetingnotes',
            name='transcript',
            field=models.TextField(blank=True, null=True, verbose_name='Transcript'),
        ),
    ]
