# Generated by Django 4.1 on 2023-05-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_meetingnotes_prompt_meetingnotes_transcript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('first_contact', 'First Contact'), ('discovery', 'Discovery'), ('evaluation', 'Evaluation'), ('document_signing', 'Document Signing'), ('win', 'Win'), ('lose', 'Lose')], default='created', max_length=255, verbose_name='Sale Status'),
        ),
    ]
