# Generated by Django 4.0 on 2023-05-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0029_alter_project_jira_code'),
        ('sales', '0017_alter_deal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingnotes',
            name='status',
            field=models.CharField(blank=True, choices=[('processing', 'Processing'), ('processed', 'Processed')], default='processing', max_length=255, verbose_name='Processing Status'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='contacts', to='development.Project', verbose_name='Projects'),
        ),
    ]
