# Generated by Django 4.0 on 2023-05-02 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0029_alter_project_jira_code'),
        ('sales', '0018_meetingnotes_status_alter_contact_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingnotes',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_notes', to='development.project', verbose_name='Project'),
        ),
    ]
