# Generated by Django 4.0 on 2023-05-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_meetingnotes_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingnotes',
            name='status',
            field=models.CharField(blank=True, choices=[('processing_audio', 'Processing Audio'), ('processing_text', 'Processing Text'), ('processed', 'Processed')], default='processing_audio', max_length=255, verbose_name='Processing Status'),
        ),
    ]
