# Generated by Django 4.0 on 2023-05-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_rename_meetingnotes_meetingnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingnote',
            name='status',
            field=models.CharField(blank=True, choices=[('processing_transcript', 'Processing Transcript'), ('processing_audio', 'Processing Audio'), ('processed', 'Processed'), ('error', 'Error')], default='processing_audio', max_length=255, verbose_name='Processing Status'),
        ),
    ]
